version: "3.9"

networks:
  liferay-ldap-network:

services:
  liferay:
    image: "liferay/portal"
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/portal-ext.properties:/opt/liferay/portal-ext.properties
    networks:
      liferay-ldap-network:
        aliases:
          - liferay.compose-network.local

  openldap:
    image: "bitnami/openldap"
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      - LDAP_ROOT=dc=liferay,dc=ldap,dc=example,dc=org
    networks:
      liferay-ldap-network:
        aliases:
          - ldap.compose-network.local
